### PR TITLE
Windows 10 Edition support + whopping stack of inventory/hotbar bug fixes

### LINKED ISSUE #1666: Enchant Unsafe
Enchant can be hacked , using a cheat! How players in my sv got sharpness 70 swords , with fire aspect  10?

Ops are banned , wen i dont use a op name i ban it, so is imposible to get on op account.
/enchant dont work  for players.
I check perms everyday , nobody is op , or got enchant perms.
Anvil is disambled . if there are any anvil exploit!

So please , fix enchanting , i beg you , stop ignoring !

Version? Any master branch -_-  !

You make too many holes so cheaters can exploit ! But nooo , if someone report 
You insult him , ignore him , or both ! -_-

### PR DESCRIPTION
**Pull request by dktapps**
## Before we begin
I would like to ask for the approval of AT LEAST 4 reviewers before this PR is merged. This is a BIG update. I also would like testers from every platform if possible - Android, iOS, Windows, GearVR (If I missed any here, feel free to correct me).

## Description
This PR has been a long time coming. But finally, it's here. Windows 10 Edition support, plus a gigantic stack of inventory and hotbar fixes all round.

## Credits (apart from myself)
I owe thanks to @extremeheat for his P.O.C. patches for Win10 Edition. The FloatingInventory concept came from there, as did the concept for the Win10 crafting fixes. The original patches can be seen [here](https://gist.github.com/extremeheat/f1e9e0b8ca884727e6a3abfc7bfdc5a3).

#### Windows 10 Edition
- Crafting
- Pressing Q to drop items one at a time works
- Left-click-drag works beautifully (even despite the DDoS)
- Issues with items not appearing in the hotbar have been mostly eliminated (I am aware that sometimes items obtained by /give do not show up, but that's not my fault.)

#### Pocket Edition
- Chests: Remember the stupid bug where you'd try to transfer items to a chest and they'd reappear in your inventory? Say goodbye to it, it's gone and buried.
- Anvils: The bug where they'd close immediately when used is gone.

#### All platforms
- HOTBAR. The hotbar has been the single most annoying buggy thing in PM since forever. Hotbar now works pretty much flawlessly on PE and Windows 10 both.
- Inventory: Every inventory spaz you care to name is fixed.
- Held item sending: Thanks to @svilex for breaking it, but that is _also_ fixed.
- Armour equipment: Bugs where armour would vanish have been fixed.
- Creative: Hotbar bugs, chest bugs, crafting bugs, bugs, bugs, bugs - fixed.

## Changes
- **An enormously powerful new inventory anti-cheat system**. It's next to impossible to dupe items, hack items in, lose items, etc. (#1626) Say goodbye to players using hacks to cheat items in.
- FloatingInventory. This is used to store items in-between transactions. If you remove and item from your inventory, it goes into here. The FloatingInventory is also currently used for Win10 crafting materials due to Win10 bugs (Windows 10 doesn't tell the host what's in the crafting grid: https://bugs.mojang.com/browse/MCPE-16366).
- Inventory transaction processing now makes use of a transaction queue. Transactions sent by the client are queued for execution. Failed transactions are retried up to 5 times. This fixes an enormous stack of issues with chests in PE.
- `PlayerInventory::setHotbarSlotIndex($index, $slot)` has been deprecated due to the massive issues it causes with Windows 10 Edition. Hotbar slot linkages will now only be changed if directly requested by the client in a MobEquipmentPacket. The reason for this is that on Win10 hotbar slots are ALWAYS linked to the first 9 slots. (Blame Mojang for allowing them to be changed on Win10.)
- Enchanting tables now open inventories per-player and do not have an inventory tied to their tile. This is because enchanting tables do not have permanent inventories, and setting enchanting table contents server-side causes clients to crash.
- Anti-cheat inventory transaction processing can now be disabled in genisys.yml. This is required for enchanting tables and anvils to work on Win10 currently (#blamemojang for Win10 bugs).
- InventoryTransactionEvent has been removed since it is impossible to pair transactions in Win10.
- Inventory custom size options have also been removed due to crashes on Win10 Edition.

## Known issues
- Anvils and enchanting tables do not currently work on Windows 10 Edition unless `inventory.allow-cheats` is set to `true` in `genisys.yml`. This is because of bugs in Win10 which make it impossible to process anti-cheats. Fixes for this will be incoming in the near future.
- Crafting: Some recipes cannot be placed anywhere in the crafting grid like they can in vanilla. My next job is an upcoming crafting rewrite in which I will attempt to resolve this issue.
- Occasional random segmentation faults have been spotted. I believe this to be a pthreads issue. If anyone can verify this or find the cause, it would be much appreciated.

## Things all devs should be aware of
- **Hacks to fix client bugs should be superficial and easy to remove once the bug is fixed.**
- Packet bouncing is the root of all evil.

## Reason to modify
Support Windows 10 Edition Beta, Gear VR Edition and fix all of the bugs mentioned above.

## Tests & Reviews
This update has been in testing for weeks. I've changed a LOT of things for this, and it's impossible for me to test every tiny little thing. I have however done very comprehensive testing and I believe that this update is now ready for production use.

### Please review things below
**I would like to require the approval of AT LEAST 4 reviewers** before this PR is merged. As I said, I've made a LOT of changes, and it's impossible for me to test every device. I have tested primarily on Windows 10 Edition and PE (Android). I'd like to ask for iOS testers and also Gear VR testers.

# Let the reviewing begin!

#### Related bugs
Close #1666

### CODE REVIEW

**Comment by Muqsit** [comment]
OMG!

File: src/pocketmine/Server.php [hunk 1]
```diff
@@ -2107,7 +2107,7 @@ public function __construct(\ClassLoader $autoloader, \ThreadedLogger $logger, $
 			}
 
 			$this->generateRecipeList();
-
+			$this->logger->warning("This build is from the Win10 Edition Beta development branch and is NOT intended for production use! Only use this build for testing purposes.");
```
Comment (robske110) [inline src/pocketmine/Server.php]: did you get rid of this commit? Maybe just DROP it :)

Comment (dktapps) [inline src/pocketmine/Server.php]: Already did locally, doing lots of squashing now

**Comment by extremeheat** [comment]
Looking good so far, no major issues I've encountered. The issue where some items don't appear until the client opens the inventory persist from what I've seen. Probably an issue with how W10E handles ContainerSetConentPacket's hotbar mappings.

Still have to look into how vanilla servers send the crafting data but I can imagine the wrong recipe IDs being sent are just client-sided issues.

**Comment by GlitchPlayer** [comment]
Looking far good, I can test this if I have free time

**Comment by dschwartz783** [comment]
Haven't noticed anything bad, but I have noticed lots of good. Seems like a solid PR so far.

**Comment by ZedCee** [comment]
Solid work.  

I'll begin testing iOS tonight and can wrap a user into testing for Android, as soon as possible.

**Comment by gaoyichuan** [comment]
Seems interesting. I'll test it this morning

**Comment by FaanMaario** [comment]
Tested, nothing bad at all, and the Win10 bugs seems to be fixed.

It works fine :D

**Comment by Muqsit** [comment]
Same, tested. Can't find bugs..!

**Comment by dktapps** [comment]
@extremeheat I've noticed that myself, but only on player join. I have however discovered something else since I made this PR that may fix the issue.

**Comment by dktapps** [comment]
Incidentally, I recommend deleting your <player>.dat file, or join as a new user. I made some tweaks to the inventory save format, so using an old one might cause some issues. @extremeheat since I recreated my profile, I haven't been able to reproduce the hotbar problems.

**Comment by AndrewBit4** [comment]
Good job :)

**Comment by dktapps** [comment]
Problems with hackers cheating items in? I forgot to mention that my new anti-cheat system puts a stop to that. :D

**Comment by FaanMaario** [comment]
@dktapps Oh yeah I just tested this, and your anti-cheat system is awesome !

Good job :D

**Comment by TheAppleGamer** [comment]
Seems amazing. I wish I could test it, but my VPS host isn't working...

**Comment by ZedCee** [comment]
Gave a decent run at it tonight.  So far, so good.  A real solid piece of work.  
There was a moment where the anti-cheat system may have been a bit voracious for me, but have not been able to reproduce. I tried several different attempts with anit-cheat on and off.  Taking two similar (possibly enchanted) items and placing them on an anvil then promptly exiting the menu only dropped one of the items.  **I could not reproduce this issue.**

However one easily reproducible error, but likely trivial for the time being, has to do with equipping items from the creative menu if they preexist within the inventory.  Sometimes, usually within the first few slots, two adjacent slots fill with said item.

Another quick review when my girlfriend's up to help test out another variety of transactions and gameplay between iOS and Android.

#### OS and versions
* Genisys: f610b9c
* PHP: 7.0.9
* Server OS: Arch Linux
* Game version: 0.15.4 iOS

**Comment by dog194** [comment]
amazing, but i don have MC win10 edison. :(

**Comment by dschwartz783** [comment]
@dog194 That’s okay. Tons of improvements for all versions. :)

**Comment by ishitatsuyuki** [comment]
Seems most people are saying OK with this, and no serious bugs exist. How about deploying this and fix when a bug report kicks in?

**Comment by NycuRO** [comment]
+1 omg best @dktapps

**Comment by dktapps** [comment]
@dog194 Lots of improvements all round, not just for Win10. I rewrote various things and the results are rather incredible.
@ZedCee Anvils are weird all round. That's next on my list of things to do, along with crafting. And as for the thing with creative... um, I'll look into it.
@ishitatsuyuki If you think that's okay, by all means. :D

**Comment by House-Kitty-Mew** [comment]
those fixes man.

**Comment by TheAppleGamer** [comment]
Everyone at my UHC server don't see any issues with it! Only problem I have encountered so far was every now and then a player .dat file has to be deleted or the server reboots.

**Comment by dktapps** [comment]
@TheAppleGamer Can you provide any more detail about this? And yes, some of the inventory save format has been modified.

**Comment by TheAppleGamer** [comment]
@dktapps I reset the .dats because I saw what you said. I then install the branch and everything was working okay. Then my friend came to test and he was able to join the first time and then he relogged and every time he went to rejoin the server would reboot. I reset his .dat file again and it started working

**Comment by dktapps** [comment]
@TheAppleGamer all right, thanks. I haven't encountered anything like that, I'll look into it. Has it happened multiple times or just that once?

**Comment by TheAppleGamer** [comment]
@dktapps Only one time so far, but I haven't had a UHC at all today. I will update you on it if it occurs again.

**Comment by TheAppleGamer** [comment]
It also looks like it removes compatibility with some plugins too.

**Comment by ZedCee** [comment]
Could this have to do with the limitation of slots?

**Comment by dktapps** [comment]
@ZedCee I doubt it. The current NBT format allows anything up to 91 slots. The only changes I made to the save format were to the hotbar data saving.

**Comment by ZedCee** [comment]
But removed the genisys.yml option for more?  Or is that just waiting a future update...?

**Comment by dktapps** [comment]
@ZedCee I removed it because a) crashes on Win10, and b) it's pointless. Plugins can do that, and in a cleaner fashion too. There should be no size-related crashes.

**Comment by dschwartz783** [comment]
@dktapps Apparently some of our users are reporting that when people die, they drop a large pile of pick axes... might be plugin-related, might not.

**Comment by dktapps** [comment]
@dschwartz783 what? I'll test that... lmao

**Comment by dktapps** [comment]
Goddammit. I took a gamble on that one to fix a tiny bug and it didn't pay off. aaargh

**Comment by ZedCee** [comment]
@dktapps I'll ask you more regarding slots on Mattermost; it's trivial at the moment.
@dschwartz783 Reminds me of a now-fixed bug that caused you to drop a random assortment of all your picked up drops since login when you closed a chest.

---

I have thoroughly tested chests, anvils, and enchanting tables, and can only say this is a far-cry better than the present state of master.  Just about any errors that come with it are trivial compared to the power at which it functions over the present production model.

I was able to produce a duplication with **_chest transactions_**.  It can be reproduced but its not necessarily an easy one to do so.  Anti-cheat makes no difference.
Load a chest with full stacks and commit transaction atrocities on it between two players.  Just keep randomly opening and closing the chest, taking and adding different amounts of items.  Eventually you may see one or two block duplicates; in my case it was the same each time; one update! block became an update!2 block or added an extra block, and I ended up with an extra portal block.  On one attempt I lost an enchantment table.

As for  **_Anvils and Enchantment Tables transactions,_** I found zero fault in the current function paradigm. Simultaneous transactions caused zero issues with anti-cheat off or on.

Finally, a solution for all our hotbar woes!  There's not a lot I can say I haven't already on this note.  It functions right.  The way it should. It got a fairly good shake down and I can say without a doubt, if merged on the fixes for the hotbar alone, new bugs would be tolerable.  (see my comment above)

To summarize, most, if not all, of our transaction issues seem to be fixed with these changes.  Functions well on multiple interacting platforms and errors and debugs are at a minimum (sometimes an anvil, not renamed, debug pops up, but most times the item still ends up renamed).  I give this a strong plus one.

---

Tested +1

#### OS and versions
* Genisys: f610b9c
* PHP: 7.0.9
* Server OS: Arch Linux
* Game version: 0.15.4 iOS and Android

**Comment by dktapps** [comment]
Erm, I wouldn't be so quick with those +1s. Seems I made a horrible mistake with the tool damage system

**Comment by dktapps** [comment]
Okay, I found the bug. As I said above, packet bouncing is the root of all evil. Keep testing, please.

**Comment by dktapps** [comment]
Okay, please try again with that commit and tell me if you can still reproduce. Please test with other tools too.

**Comment by dktapps** [comment]
Damn. Still affects adventure mode.

**Comment by dktapps** [comment]
Okay, fixed. Please test again.

**Comment by ZedCee** [comment]
Seems good on my end.

**Comment by dschwartz783** [comment]
@dktapps I'll get the changes pushed to our hub as soon as I can to test :) I never actually experienced the bug myself, so I can't be certain how to test for it.

**Comment by TheAppleGamer** [comment]
@dktapps Everyone had almost no issues! 56 people said they had no issues during the UHC. Only 5 said they did and that was that their chestplate would disappear off of them.

**Comment by TheAppleGamer** [comment]
Also @dktapps I hate to be that guy, but some of the code for plugins are useless. For example my HandSmelt no longer works. 

public function onHand(PlayerItemHeldEvent $event);
    $player = $event->getPlayer;
    $item = $player->getInventory()->getItemInHand();
No longer works anymore.

**Comment by robske110** [comment]
Hmmm. Breaking that is indeed bad

**Comment by thebigsmileXD** [comment]
:*

File: README.md [hunk 2]
```diff
@@ -14,7 +14,7 @@ Genisys
 	You should have received a copy of the GNU General Public License
 	along with this program.  If not, see <http://www.gnu.org/licenses/>.
 
-__Feature-rich Minecraft: Pocket Edition server software__
+__Feature-rich server software for Minecraft: Pocket Edition and Windows 10 Edition Beta__
```
Comment (thebigsmileXD) [inline README.md]: its not beta anymore

File: src/pocketmine/Player.php [hunk 3]
```diff
@@ -172,9 +172,11 @@ class Player extends Human implements CommandSender, InventoryHolder, ChunkLoade
...
 	const SPECTATOR = 3;
 	const VIEW = Player::SPECTATOR;
-
-	const SURVIVAL_SLOTS = 36;
-	const CREATIVE_SLOTS = 112;
+	
+	const CRAFTING_SMALL = 0;
+	const CRAFTING_BIG = 1;
+	const CRAFTING_ANVIL = 2;
+	const CRAFTING_ENCHANT = 3;
```
Comment (thebigsmileXD) [inline src/pocketmine/Player.php]: wasn't this in inventory type?

File: README.md (hunk 2 above)
Comment (robske110) [inline README.md]: I think it os 🤔

File: src/pocketmine/Player.php [hunk 4]
```diff
@@ -3284,34 +3223,74 @@ public function handleDataPacket(DataPacket $packet){
...
-					unset($this->windowIndex[$packet->windowid]);
+				}
+
+				/**
+				 * Drop anything still left in the crafting inventory
+				 * This will usually never be needed since Windows 10 clients will send DropItemPackets
+				 * which will cause this to happen anyway, but this is here for when transactions
+				 * fail and items end up stuck in the crafting inventory.
+				 */
+				foreach($this->getFloatingInventory()->getContents() as $item){
```
Comment (thebigsmileXD) [inline src/pocketmine/Player.php]: What the hell is even a floating inventory? I know floating nametags, but floating inventories simply don't exist

Comment (robske110) [inline src/pocketmine/Player.php]: If you pickup a item and have it under your mouse in win10

File: src/pocketmine/Player.php [hunk 5]
```diff
@@ -3284,34 +3223,74 @@ public function handleDataPacket(DataPacket $packet){
...
 
-				if($recipe === null or (($recipe instanceof BigShapelessRecipe or $recipe instanceof BigShapedRecipe) and $this->craftingType === 0)){
+					if($recipe === null){
+						//Item renamed
+						if(!$anvilInventory->onRename($this, $packet->output[0])){
+							$this->getServer()->getLogger()->debug($this->getName()." failed to rename an item in an anvil");
+							$this->inventory->sendContents($this);
+						}
+					}else{
+						//TODO: Anvil crafting recipes
```
Comment (thebigsmileXD) [inline src/pocketmine/Player.php]: i may help with these.

File: src/pocketmine/Player.php [hunk 6]
```diff
@@ -3322,131 +3301,192 @@ public function handleDataPacket(DataPacket $packet){
 						$item->setDamage(null);
 					}
 
-					if($i < 9 and $item->getId() > 0){
+					if($i < 9 and $item->getId() > 0){ //TODO: Get rid of this hack.
```
Comment (thebigsmileXD) [inline src/pocketmine/Player.php]: whats the reason to leave it in? it sets every count to 1.

File: src/pocketmine/Player.php [hunk 7]
```diff
@@ -3322,131 +3301,192 @@ public function handleDataPacket(DataPacket $packet){
...
-				}else{
-					$canCraft = false;
-				}
 
-				/** @var Item[] $ingredients */
-				$canCraft = true;//0.13.1大量物品本地配方出现问题,无法解决,使用极端(唯一)方法修复.
-				$ingredients = $packet->input;
-				$result = $packet->output[0];
+					//Nasty hack. TODO: Get rid
+					$canCraft = true;//0.13.1大量物品本地配方出现问题,无法解决,使用极端(唯一)方法修复.
```
Comment (thebigsmileXD) [inline src/pocketmine/Player.php]: whatever this means

File: src/pocketmine/Player.php (hunk 4 above)
Comment (ishitatsuyuki) [inline src/pocketmine/Player.php]: Please read the description of this PR.

**Comment by thebigsmileXD** [comment]
> (I am aware that sometimes items obtained by /give do not show up, but that's not my fault.)

File: README.md (hunk 2 above)
Comment (thebigsmileXD) [inline README.md]: Damn it, it is. Well i guess it stays beta forever xD

File: src/pocketmine/Player.php (hunk 4 above)
Comment (thebigsmileXD) [inline src/pocketmine/Player.php]: But still not floating. its kind of more an transaction inventory

**Comment by dktapps** [comment]
@theapplegamer $event->getplayer()

Noob

File: src/pocketmine/Player.php (hunk 6 above)
Comment (dktapps) [inline src/pocketmine/Player.php]: @thebigsmileXD It's a hack because some idiot gave individual recipe ingredients counts and couldn't be bothered to fix it. Take a door for example: you assume 6 wood, yeah? Some fool made _each_ item 6 wood, so it would actually cost you 36. That's why this is here. I'm going to fix that when I rewrite crafting.

File: src/pocketmine/Player.php (hunk 7 above)
Comment (dktapps) [inline src/pocketmine/Player.php]: Another dirty (~~chinese~~) hack from people too lazy to fix things the right way.

File: src/pocketmine/Player.php (hunk 4 above)
Comment (dktapps) [inline src/pocketmine/Player.php]: I _could_ refactor it, but I like FloatingInventory. Items that are "floating", as in somewhere in between

File: src/pocketmine/Player.php (hunk 3 above)
Comment (dktapps) [inline src/pocketmine/Player.php]: @thebigsmileXD That's for inventory network IDs. These are for the purposes of the server tracking what type of crafting the client is performing.

**Comment by dktapps** [comment]
@dschwartz783 Mine with any tool, then open/close something like a chest or furnace so it drops your floating inventory contents. Result _was_ lots of tools and unable to pick items up. I think it's fixed now though.

**Comment by TheAppleGamer** [comment]
@dktapps It worked fine before the Windows 10 branch. So it doesn't qualify as noob if things change.

**Comment by dktapps** [comment]
@TheAppleGamer It's not my fault you're doing it wrong. Go correct your code and see if it still happens.

**Comment by TheAppleGamer** [comment]
@dktapps Thing is you can't throw the blame on me if everything worked fine on the master branch using on Hand() Windows 10 branch broke a few plugins. SuperBar, HandSmelt, JoinEffects and that's about it that I know of.

**Comment by dktapps** [comment]
Repeat: Go correct your code and see if it still happens. If you don't have anything useful to add to the conversation don't bother. This is a dev discussion, not a squabble.

**Comment by dktapps** [comment]
I think we're _definitely_ going to need fresh API documentation generating after this update though. And I should bump the API version.

File: src/pocketmine/Player.php (hunk 7 above)
Comment (robske110) [inline src/pocketmine/Player.php]: maybe work on removing it?

Comment (dktapps) [inline src/pocketmine/Player.php]: @robske110 that will be done when I rewrite crafting

File: src/pocketmine/inventory/PlayerInventory.php [hunk 8]
```diff
@@ -490,7 +493,7 @@ public function sendContents($target){
 			if($player === $this->getHolder()){
 				for($i = 0; $i < $this->getHotbarSize(); ++$i){
 					$index = $this->getHotbarSlotIndex($i);
-					$pk->hotbar[$i] = ($index >= 0 ? $index + $this->getHotbarSize() : -1);
+					$pk->hotbar[$i] = $index <= -1 ? -1 : $index + $this->getHotbarSize();
```
Comment (dktapps) [inline src/pocketmine/inventory/PlayerInventory.php]: This will probably make absolutely no difference.

**Comment by dktapps** [comment]
@TheAppleGamer Would you like to retry with the latest commit?

**Comment by TheAppleGamer** [comment]
@dktapps Still doesn't work :/

**Comment by ZedCee** [comment]
Hotbar wrangling/fishing is back.

**Comment by dktapps** [comment]
@ZedCee what do you mean?

**Comment by ZedCee** [comment]
Couldn't hold onto or place glowing obsidian again.  The above fixed it.

**Comment by AndreyNazarchuk** [comment]
Still need a tester? I have full edition.

**Comment by GlitchPlayer** [comment]
Solid work! Just tested.

**Comment by dktapps** [comment]
Thanks all. And yes, the more testers the better. I want to catch as many possible issues as possible before this is merged.

**Comment by House-Kitty-Mew** [comment]
In GearVR, when you try to switch to creative all ur items gets stuck permanently and cant switch out anything even after switching back, only a player .dat wipe fixes this, though this might be a plugin issue, iam still going through the errors and stuff myself, but i cant find a plugin log so it makes me think its a server issue.

**Comment by Adam1609** [comment]
The best Win10 update I had ever used in my life!

**Comment by dktapps** [comment]
@TheAppleGamer I found your bug and will fix it shortly

**Comment by dktapps** [comment]
@TheAppleGamer Would you like to retry with the latest commit? That should fix the issue.

**Comment by GlitchPlayer** [comment]
Did InventoryTransactionEvent was removed?

**Comment by GlitchPlayer** [comment]
Also I found a new bug

###How to reproduced
1. Hold any item in your hotbar
2. do /give usrname anyitem
3. You will notice no items will be given to you.

###OS and versions
Version: c93b8c5
Server OS: Windows 10
Client version: Windows 10 edition

**Comment by dktapps** [comment]
@GlitchPlayer I can't reproduce that. And yes, InventoryTransactionEvent was removed (please see description)

**Comment by robske110** [comment]
Is there any equivalence for InventoryTransactionEvent? Because we need this even really hard.

**Comment by robske110** [comment]
And is there any way for us to set an Item in the hand or to switch the hotbar index.

**Comment by dktapps** [comment]
@robske110 I'm **going to** add a new event for individual slot changes that can replace that.

**Comment by robske110** [comment]
second question? :)

**Comment by dktapps** [comment]
@robske110 setHotbarSlotIndex() Same as always

**Comment by ZedCee** [comment]
Have been using this for a bit now.
Functions quite well on any mobile device.  No more complaints about the hotbar or chests from my girlfriend.  

I can only note a few random errors, but I believe those to be preexisting issues from the `master` that we can now venture out and tackle.

This needs to now be considered for further implementation of PRs as well

---

Tested and stopped using master after. +1

#### OS and versions
* Genisys: c93b8c5
* PHP: 7.0.9 (from Arch)
* Server OS: Arch Linux
* Game version: 0.15.4 iOS and Android

**Comment by thebigsmileXD** [comment]
Well, just to mention: the MCPE devs still didn't respond to the issue -.-

Btw, i amso need the transaction event. My VillagerTradePE and Bedwars depend on those ;)

**Comment by dktapps** [comment]
@iTXTech/trusted Please test and review.

**Comment by ZedCee** [comment]
@iTXTech/trusted Be really nice to start considering these changes for future PRs soon :+1:

**Comment by ishitatsuyuki** [comment]
Let's take action. Code review +1

**Comment by dktapps** [comment]
@ZedCee The PullApprove resets when I push, would you test and review again with the latest commit?

**Comment by ZedCee** [comment]
Tested. +1

#### OS and versions
* Genisys: 4b26b36bfe4c9a64d5c74d2d4add27528501a762
* PHP: 7.0.9 (from Arch)
* Server OS: Arch Linux
* Game version: 0.15.4 iOS and Android

**Comment by dktapps** [comment]
Tested on Win10, no issues to speak of. Shoot first, ask questions later.
