### PR TITLE
Fix bad effects on Creative, close #2193

### LINKED ISSUE #2193: Potion damage in Creative
#### Issue description

When using a harming potion you can kill players in creative
#### Steps to reproduce the issue

Get a harming potion and a player
Make sure the player is in gmc
hit then with harming
#### OS and versions

* Genisys: 379a533
* PHP: 7.0.12
* Server OS: Windows 10
* Game version: 0.16.1

#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

### PR DESCRIPTION
**Pull request by iPocket**

### CODE REVIEW

File: src/pocketmine/Player.php [hunk 1]
```diff
@@ -4337,4 +4337,14 @@ public static function getChunkCacheFromData($chunkX, $chunkZ, $payload, $orderi
 		return $pk;
 	}
 
-}
+	/**
+	 * @param Effect
+	*/
+	public function addEffect(Effect $effect){//Overwrite
+		if($effect->isBad() && $this->isCreative()){
+			return false;
```
Comment (dktapps) [inline src/pocketmine/Player.php]: does this method have a return value? if so, you haven't returned anything below.

Comment (iPocket) [inline src/pocketmine/Player.php]: returning void, ok?
